### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by RoboTehnik** [cosmocode/nsexport#8]
Warning: require_once(/home/u304365872/public_html/lib/plugins/nsexport/../../../inc/auth/basic.class.php) [function.require-once]: failed to open stream: No such file or directory in /home/u304365872/public_html/lib/plugins/nsexport/export.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '/home/u304365872/public_html/lib/plugins/nsexport/../../../inc/auth/basic.class.php' (include_path='.:/opt/php-5.2/pear') in /home/u304365872/public_html/lib/plugins/nsexport/export.php on line 5

**Comment by Naxmeify** [comment]
same error

**Comment by zonix** [comment]
Looks like the plugin isn't compatible with recent DW releases. I've commented out the offending line but now I'm stuck with an empty export page (DW 2015-08-10a)
